name = "mazzgordwebsite"
compatibility_date = "2026-05-21"
main = "worker.js"

[assets]
directory = "./dist/public"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"
binding = "ASSETS"

[[routes]]
pattern = "mazzgord.com/*"
zone_name = "mazzgord.com"
