INSERT INTO services (sku, slug, name, description, category, source_language, target_language, unit, base_price, sort_order, options) VALUES
('TR-EN-TRANSLATION', 'english-turkish-translation', 'İngilizce → Türkçe Çeviri', 'Profesyonel İngilizce→Türkçe çeviri hizmeti. Sayfa başına ücretlendirilir.', 'translation', 'en', 'tr', 'page', 125, 1, '[{"key":"urgent","label":"Acil Çeviri","type":"surcharge_percent","value":30},{"key":"notary","label":"Noter Onayı","type":"fixed_price","value":1750},{"key":"apostille","label":"Apostil","type":"fixed_price","value":350},{"key":"shipping","label":"Kargo","type":"fixed_price","value":250}]'),
('EN-TR-TRANSLATION', 'turkish-english-translation', 'Türkçe → İngilizce Çeviri', 'Profesyonel Türkçe→İngilizce çeviri hizmeti. Sayfa başına ücretlendirilir.', 'translation', 'tr', 'en', 'page', 125, 2, '[{"key":"urgent","label":"Acil Çeviri","type":"surcharge_percent","value":30},{"key":"notary","label":"Noter Onayı","type":"fixed_price","value":1750},{"key":"apostille","label":"Apostil","type":"fixed_price","value":350},{"key":"shipping","label":"Kargo","type":"fixed_price","value":250}]'),
('DE-TR-TRANSLATION', 'german-turkish-translation', 'Almanca → Türkçe Çeviri', 'Profesyonel Almanca→Türkçe çeviri hizmeti. Sayfa başına ücretlendirilir.', 'translation', 'de', 'tr', 'page', 150, 3, '[{"key":"urgent","label":"Acil Çeviri","type":"surcharge_percent","value":30},{"key":"notary","label":"Noter Onayı","type":"fixed_price","value":1750},{"key":"apostille","label":"Apostil","type":"fixed_price","value":350},{"key":"shipping","label":"Kargo","type":"fixed_price","value":250}]'),
('TR-DE-TRANSLATION', 'turkish-german-translation', 'Türkçe → Almanca Çeviri', 'Profesyonel Türkçe→Almanca çeviri hizmeti. Sayfa başına ücretlendirilir.', 'translation', 'tr', 'de', 'page', 150, 4, '[{"key":"urgent","label":"Acil Çeviri","type":"surcharge_percent","value":30},{"key":"notary","label":"Noter Onayı","type":"fixed_price","value":1750},{"key":"apostille","label":"Apostil","type":"fixed_price","value":350},{"key":"shipping","label":"Kargo","type":"fixed_price","value":250}]'),
('FR-TR-TRANSLATION', 'french-turkish-translation', 'Fransızca → Türkçe Çeviri', 'Profesyonel Fransızca→Türkçe çeviri hizmeti. Sayfa başına ücretlendirilir.', 'translation', 'fr', 'tr', 'page', 150, 5, '[{"key":"urgent","label":"Acil Çeviri","type":"surcharge_percent","value":30},{"key":"notary","label":"Noter Onayı","type":"fixed_price","value":1750},{"key":"apostille","label":"Apostil","type":"fixed_price","value":350},{"key":"shipping","label":"Kargo","type":"fixed_price","value":250}]'),
('TR-FR-TRANSLATION', 'turkish-french-translation', 'Türkçe → Fransızca Çeviri', 'Profesyonel Türkçe→Fransızca çeviri hizmeti. Sayfa başına ücretlendirilir.', 'translation', 'tr', 'fr', 'page', 150, 6, '[{"key":"urgent","label":"Acil Çeviri","type":"surcharge_percent","value":30},{"key":"notary","label":"Noter Onayı","type":"fixed_price","value":1750},{"key":"apostille","label":"Apostil","type":"fixed_price","value":350},{"key":"shipping","label":"Kargo","type":"fixed_price","value":250}]'),
('TR-EN-SWORN', 'english-turkish-sworn', 'İngilizce → Türkçe Yeminli Tercüme', 'Yeminli tercüman tarafından yapılan İngilizce→Türkçe resmi çeviri. Sayfa başına ücretlendirilir.', 'sworn', 'en', 'tr', 'page', 187.5, 10, '[{"key":"urgent","label":"Acil Çeviri","type":"surcharge_percent","value":30},{"key":"notary","label":"Noter Onayı","type":"fixed_price","value":1750},{"key":"apostille","label":"Apostil","type":"fixed_price","value":350},{"key":"shipping","label":"Kargo","type":"fixed_price","value":250}]'),
('EN-TR-SWORN', 'turkish-english-sworn', 'Türkçe → İngilizce Yeminli Tercüme', 'Yeminli tercüman tarafından yapılan Türkçe→İngilizce resmi çeviri. Sayfa başına ücretlendirilir.', 'sworn', 'tr', 'en', 'page', 187.5, 11, '[{"key":"urgent","label":"Acil Çeviri","type":"surcharge_percent","value":30},{"key":"notary","label":"Noter Onayı","type":"fixed_price","value":1750},{"key":"apostille","label":"Apostil","type":"fixed_price","value":350},{"key":"shipping","label":"Kargo","type":"fixed_price","value":250}]'),
('DE-TR-SWORN', 'german-turkish-sworn', 'Almanca → Türkçe Yeminli Tercüme', 'Yeminli tercüman tarafından yapılan Almanca→Türkçe resmi çeviri. Sayfa başına ücretlendirilir.', 'sworn', 'de', 'tr', 'page', 225, 12, '[{"key":"urgent","label":"Acil Çeviri","type":"surcharge_percent","value":30},{"key":"notary","label":"Noter Onayı","type":"fixed_price","value":1750},{"key":"apostille","label":"Apostil","type":"fixed_price","value":350},{"key":"shipping","label":"Kargo","type":"fixed_price","value":250}]'),
('TR-DE-SWORN', 'turkish-german-sworn', 'Türkçe → Almanca Yeminli Tercüme', 'Yeminli tercüman tarafından yapılan Türkçe→Almanca resmi çeviri. Sayfa başına ücretlendirilir.', 'sworn', 'tr', 'de', 'page', 225, 13, '[{"key":"urgent","label":"Acil Çeviri","type":"surcharge_percent","value":30},{"key":"notary","label":"Noter Onayı","type":"fixed_price","value":1750},{"key":"apostille","label":"Apostil","type":"fixed_price","value":350},{"key":"shipping","label":"Kargo","type":"fixed_price","value":250}]');

INSERT INTO services (sku, slug, name, description, category, unit, base_price, sort_order, options) VALUES
('NOTARY-APPROVAL', 'notary-approval', 'Noter Onayı', 'Çeviri belgesinin noter tarafından onaylanması. Belge başına tek seferlik ücret.', 'official', 'document', 1750, 20, '[]'),
('APOSTILLE', 'apostille', 'Apostil', 'Belgenin apostil ile yurtdışı geçerliliği. Belge başına tek seferlik ücret.', 'official', 'document', 350, 21, '[]'),
('URGENT-TRANSLATION', 'urgent-translation', 'Acil Çeviri Hizmeti', 'Acil çeviri önceliği. Normal sürenin yarısı kadar teslim. Çeviri tutarına %30 ek ücret.', 'extra', 'page', 0, 30, '[]'),
('PHYSICAL-DELIVERY', 'physical-delivery', 'Fiziksel Teslimat (Kargo)', 'Çevrilmiş belgelerin fiziksel olarak kargo ile teslimi. Tek seferlik ücret.', 'extra', 'item', 250, 31, '[]'),
('SWORN-TRANSLATION', 'sworn-translation', 'Yeminli Tercüme (Genel)', 'Yeminli tercüman tarafından yapılan genel belge çevirisi. Sayfa başına ücretlendirilir.', 'sworn', 'page', 187.5, 14, '[{"key":"urgent","label":"Acil Çeviri","type":"surcharge_percent","value":30},{"key":"notary","label":"Noter Onayı","type":"fixed_price","value":1750},{"key":"apostille","label":"Apostil","type":"fixed_price","value":350},{"key":"shipping","label":"Kargo","type":"fixed_price","value":250}]');
