import { ArrowLeft, CheckCircle2, Shield, Clock, Globe, Zap, Lock } from "lucide-react";
import Breadcrumb from "@/components/Breadcrumb";
import { useState } from "react";
export default function AcilTercume() {
  const [mobileOpen, setMobileOpen] = useState(false);
  return (
    <div className="min-h-screen bg-background">
      <nav className="sticky top-0 z-50 bg-background border-b border-border">
        <div className="container mx-auto px-4 py-4 flex justify-between items-center">
          <a href="/" className="flex items-center gap-2 text-muted-foreground hover:text-primary transition"><ArrowLeft className="w-5 h-5" /> Ana Sayfa</a>
          <div className="hidden md:flex gap-8">
            <a href="/fiyatlar" className="text-foreground hover:text-primary transition">Fiyatlar</a>
            <a href="/blog" className="text-foreground hover:text-primary transition">Blog</a>
            <a href="/hakkimizda" className="text-foreground hover:text-primary transition">Hakkımda</a>
            <a href="/teklif" className="bg-primary text-primary-foreground px-5 py-2 rounded-lg font-medium hover:bg-primary/90 transition no-underline">Teklif Al</a>
          </div>
          <button className="md:hidden flex flex-col gap-1.5 p-2 cursor-pointer bg-transparent border-none z-60" onClick={() => setMobileOpen(!mobileOpen)}>
            <span className={`block w-6 h-0.5 bg-foreground rounded transition-all duration-300 ${mobileOpen ? "rotate-45 translate-y-[7px]" : ""}`}></span>
            <span className={`block w-6 h-0.5 bg-foreground rounded transition-all duration-300 ${mobileOpen ? "opacity-0" : ""}`}></span>
            <span className={`block w-6 h-0.5 bg-foreground rounded transition-all duration-300 ${mobileOpen ? "-rotate-45 -translate-y-[7px]" : ""}`}></span>
          </button>
          {mobileOpen && (
            <>
              <div className="fixed inset-0 bg-black/50 z-40 md:hidden" onClick={() => setMobileOpen(false)}></div>
              <div className="fixed top-0 right-0 w-72 h-full bg-background z-50 shadow-2xl p-8 pt-24 flex flex-col gap-2 md:hidden">
                <a href="/fiyatlar" className="block px-4 py-3 text-foreground hover:bg-accent rounded-lg text-lg no-underline transition" onClick={() => setMobileOpen(false)}>Fiyatlar</a>
                <a href="/blog" className="block px-4 py-3 text-foreground hover:bg-accent rounded-lg text-lg no-underline transition" onClick={() => setMobileOpen(false)}>Blog</a>
                <a href="/hakkimizda" className="block px-4 py-3 text-foreground hover:bg-accent rounded-lg text-lg no-underline transition" onClick={() => setMobileOpen(false)}>Hakkımda</a>
                <a href="/teklif" className="block px-4 py-3 bg-primary text-primary-foreground font-medium hover:bg-primary/90 rounded-lg text-lg no-underline transition" onClick={() => setMobileOpen(false)}>Teklif Al</a>
              </div>
            </>
          )}
        </div>
      </nav>
      <div className="container mx-auto px-4 py-12 max-w-4xl">
        <Breadcrumb items={[{label: "Hizmetler", href: "/"}, {label: "Acil Tercüme"}]} />
        <h1 className="text-4xl font-bold text-primary mb-4">Acil Tercüme | Hızlı İngilizce-Türkçe Yeminli Çeviri</h1>
        <p className="text-xl text-muted-foreground mb-8">Acil çeviri ihtiyacınız için aynı gün teslimat. Belgenizi gönderin, öncelikli olarak çevirip teslim edeyim.</p>
        <div className="grid md:grid-cols-3 gap-6 mb-12">
<div className="flex gap-4 p-6 bg-card rounded-xl border border-border"><Zap className="w-8 h-8 text-primary flex-shrink-0" /><div><h3 className="font-bold mb-2">Aynı Gün Teslimat</h3><p className="text-muted-foreground text-sm">Acil taleplerde belgenizi aynı gün içinde teslim ederim.</p></div></div><div className="flex gap-4 p-6 bg-card rounded-xl border border-border"><Clock className="w-8 h-8 text-primary flex-shrink-0" /><div><h3 className="font-bold mb-2">Öncelikli İşlem</h3><p className="text-muted-foreground text-sm">Acil çeviriler öncelikli sıraya alınır, bekleme süresini kısaltır.</p></div></div><div className="flex gap-4 p-6 bg-card rounded-xl border border-border"><Globe className="w-8 h-8 text-primary flex-shrink-0" /><div><h3 className="font-bold mb-2">İngilizce-Türkçe</h3><p className="text-muted-foreground text-sm">İngilizce-Türkçe dil çiftinde uzman yeminli tercüme.</p></div></div>
        </div>
<div className="bg-secondary/30 rounded-xl p-8 mb-8"><h2 className="text-2xl font-bold text-primary mb-4">Acil Tercüme Nedir?</h2><p className="text-muted-foreground leading-relaxed mb-4">Acil tercüme, normal teslim süresinden daha kısa sürede tamamlanması gereken çeviri talepleridir. Vize başvurusu son günü, konsolosluk randevusu, mahkeme dosyası veya acil iş başvurusu gibi durumlarda ihtiyaç duyulur.</p><p className="text-muted-foreground leading-relaxed mb-4">Acil çevirilerde belgenizi öncelikli olarak işler ve aynı gün içinde teslim ederim. Çeviri kalitesinden ödün vermeden hızlı teslimat sağlarım.</p><p className="text-muted-foreground leading-relaxed mb-4">İngilizce-Türkçe dil çiftinde acil yeminli tercüme yapıyorum. Belgenizi gönderin, durumunuzu açıklayın; en kısa sürede dönüş yapayım.</p></div>
<div className="bg-secondary/30 rounded-xl p-8 mb-8"><h2 className="text-2xl font-bold text-primary mb-4">Acil Tercüme Ne Zaman Gerekir?</h2><div className="grid md:grid-cols-2 gap-4"><div className="flex items-center gap-3 p-3 bg-card rounded-lg border border-border"><CheckCircle2 className="w-5 h-5 text-primary flex-shrink-0" /><span className="text-foreground">Vize başvurusu son günü</span></div><div className="flex items-center gap-3 p-3 bg-card rounded-lg border border-border"><CheckCircle2 className="w-5 h-5 text-primary flex-shrink-0" /><span className="text-foreground">Konsolosluk randevusu yaklaştığında</span></div><div className="flex items-center gap-3 p-3 bg-card rounded-lg border border-border"><CheckCircle2 className="w-5 h-5 text-primary flex-shrink-0" /><span className="text-foreground">Acil iş başvurusu</span></div><div className="flex items-center gap-3 p-3 bg-card rounded-lg border border-border"><CheckCircle2 className="w-5 h-5 text-primary flex-shrink-0" /><span className="text-foreground">Mahkeme dosyası teslim süresi</span></div><div className="flex items-center gap-3 p-3 bg-card rounded-lg border border-border"><CheckCircle2 className="w-5 h-5 text-primary flex-shrink-0" /><span className="text-foreground">Acil denklik başvurusu</span></div><div className="flex items-center gap-3 p-3 bg-card rounded-lg border border-border"><CheckCircle2 className="w-5 h-5 text-primary flex-shrink-0" /><span className="text-foreground">Son dakika belge teslimi</span></div></div></div>
<div className="mb-8"><h2 className="text-2xl font-bold text-primary mb-6">Acil Tercüme Süreci: Adım Adım</h2><div className="space-y-4"><div className="flex gap-4 p-5 bg-card rounded-lg border border-border"><div className="flex-shrink-0 w-10 h-10 rounded-full bg-primary text-white flex items-center justify-center font-bold text-lg">1</div><div><h3 className="text-lg font-semibold text-primary mb-2">Belgeyi Gönderin</h3><p className="text-muted-foreground">Belgenizin fotoğrafını WhatsApp'tan gönderin ve acil durumunuzu açıklayın. Mümkün olan en kısa süreyi belirtirim.</p></div></div><div className="flex gap-4 p-5 bg-card rounded-lg border border-border"><div className="flex-shrink-0 w-10 h-10 rounded-full bg-primary text-white flex items-center justify-center font-bold text-lg">2</div><div><h3 className="text-lg font-semibold text-primary mb-2">Hızlı Teklif</h3><p className="text-muted-foreground">Belgeyi inceleyip hemen teklif veririm. Onayladığınızda çeviri hemen başlar.</p></div></div><div className="flex gap-4 p-5 bg-card rounded-lg border border-border"><div className="flex-shrink-0 w-10 h-10 rounded-full bg-primary text-white flex items-center justify-center font-bold text-lg">3</div><div><h3 className="text-lg font-semibold text-primary mb-2">Öncelikli Çeviri</h3><p className="text-muted-foreground">Belgenizi öncelikli sıraya alır, aynı gün içinde çevirir, imzalar ve kaşelerim.</p></div></div><div className="flex gap-4 p-5 bg-card rounded-lg border border-border"><div className="flex-shrink-0 w-10 h-10 rounded-full bg-primary text-white flex items-center justify-center font-bold text-lg">4</div><div><h3 className="text-lg font-semibold text-primary mb-2">Hızlı Teslim</h3><p className="text-muted-foreground">Çevrilmiş belgenizi dijital (PDF) olarak aynı gün içinde teslim ederim. Kargo gerekiyorsa en hızlı seçeneği kullanırım.</p></div></div></div></div>
<div className="bg-secondary/30 rounded-xl p-8 mb-8"><h2 className="text-2xl font-bold text-primary mb-4">Acil Tercüme Fiyatları</h2><p className="text-muted-foreground leading-relaxed mb-4">Acil tercüme fiyatı, normal çeviri ücretine %30-50 acil işlem ek ücreti eklenerek belirlenir. Belge türü ve teslim süresi fiyatı etkiler. Noter onayı gerektiğinde, gerçek noter bedeli makbuzla teyit edilir.</p><p className="text-muted-foreground leading-relaxed mb-4">Net teklif için belgenizin fotoğrafını WhatsApp'tan gönderin ve acil durumunuzu açıklayın. Hemen dönüş yapıyorum.</p></div>
<div className="mb-8"><h2 className="text-2xl font-bold text-primary mb-6">Sıkça Sorulan Sorular</h2><div className="space-y-4"><div className="p-5 bg-card rounded-lg border border-border"><h3 className="font-bold text-primary mb-2">Acil tercüme nedir?</h3><p className="text-muted-foreground">Acil tercüme, normal süreden daha kısa sürede tamamlanması gereken çeviri talebidir. Vize son günü, konsolosluk randevusu veya acil iş başvurusu gibi durumlarda ihtiyaç duyulur.</p></div><div className="p-5 bg-card rounded-lg border border-border"><h3 className="font-bold text-primary mb-2">Acil çeviri aynı gün teslim edilir mi?</h3><p className="text-muted-foreground">Evet, çoğu durumda aynı gün içinde teslim edilir. Belgenizi gönderin, durumunuzu açıklayın; en kısa süreyi belirtirim.</p></div><div className="p-5 bg-card rounded-lg border border-border"><h3 className="font-bold text-primary mb-2">Acil tercüme fiyatı normalden farklı mıdır?</h3><p className="text-muted-foreground">Evet, acil taleplerde %30-50 arası acil işlem ek ücreti uygulanır. Belge türü ve teslim süresi fiyatı belirler.</p></div><div className="p-5 bg-card rounded-lg border border-border"><h3 className="font-bold text-primary mb-2">Hangi belgeler için acil tercüme yapabilirsiniz?</h3><p className="text-muted-foreground">Pasaport, diploma, transkript, vize belgeleri, adli sicil, nüfus kayıt örneği ve diğer resmi belgeler için acil çeviri yapabilirim.</p></div><div className="p-5 bg-card rounded-lg border border-border"><h3 className="font-bold text-primary mb-2">Acil tercüme için nasıl başvururum?</h3><p className="text-muted-foreground">Belgenizin fotoğrafını WhatsApp'tan gönderin ve acil durumunuzu açıklayın. Hemen teklif veririm ve onayladığınızda çeviri başlar.</p></div></div></div>
<div className="mb-8"><h2 className="text-2xl font-bold text-primary mb-6">İlgili Blog Yazıları</h2><div className="grid md:grid-cols-2 gap-4 mb-8"><a href="/blog/yeminli-tercume" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Yeminli Tercüme Süreci</a><a href="/blog/yeminli-tercume-fiyatlari-2026" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Yeminli Tercüme Fiyatları 2026</a><a href="/blog/vize-formatlari" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Vize Çeviri Formatları Rehberi</a></div>
<h2 className="text-2xl font-bold text-primary mb-6">Diğer Hizmetler</h2><div className="grid md:grid-cols-2 gap-4"><a href="/yeminli-tercume" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Yeminli Tercüme</a><a href="/ingilizce-turkce-ceviri" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">İngilizce-Türkçe Çeviri</a><a href="/pasaport-ceviri" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Pasaport Çevirisi</a><a href="/diploma-ceviri" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Diploma Çevirisi</a><a href="/transkript-ceviri" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Transkript Çevirisi</a><a href="/vize-ceviri" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Vize Çevirisi</a><a href="/teknik-ceviri" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Teknik Çeviri</a><a href="/akademik-ceviri" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Akademik Çeviri</a><a href="/fiyatlar" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Çeviri Fiyatları</a><a href="/teklif" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Teklif Al</a></div></div>
<div className="bg-primary text-primary-foreground rounded-xl p-8 text-center"><h2 className="text-2xl font-bold mb-4">Acil Tercüme Teklifi Alın</h2><p className="mb-6 opacity-90">Belgenizi gönderin, aynı gün teslimat için hemen dönüş yapayım.</p><div className="flex flex-col sm:flex-row gap-4 justify-center"><a href="/teklif" className="px-8 py-3 bg-accent hover:bg-accent/90 text-accent-foreground rounded-lg font-medium transition">Teklif Alın</a><a href="https://wa.me/905386295040" target="_blank" className="px-8 py-3 bg-green-500 hover:bg-green-600 text-white rounded-lg font-medium transition">WhatsApp ile Ulaşın</a></div></div>
      </div>
    </div>
  );
}