import { ArrowLeft, CheckCircle2, Shield, Clock, FileText, Globe } from "lucide-react";
import Breadcrumb from "@/components/Breadcrumb";
import { useState } from "react";
export default function DenizliApostilTercume() {
  const [mobileOpen, setMobileOpen] = useState(false);
  return (
    <div className="min-h-screen bg-background">
<nav className="sticky top-0 z-50 bg-background border-b border-border"><div className="container mx-auto px-4 py-4 flex justify-between items-center"><a href="/" className="flex items-center gap-2 text-muted-foreground hover:text-primary transition"><ArrowLeft className="w-5 h-5" /> Ana Sayfa</a><div className="hidden md:flex gap-8"><a href="/fiyatlar" className="text-foreground hover:text-primary transition">Fiyatlar</a><a href="/blog" className="text-foreground hover:text-primary transition">Blog</a><a href="/hakkimizda" className="text-foreground hover:text-primary transition">Hakkımda</a><a href="/teklif" className="bg-primary text-primary-foreground px-5 py-2 rounded-lg font-medium hover:bg-primary/90 transition no-underline">Teklif Al</a></div><button className="md:hidden flex flex-col gap-1.5 p-2 cursor-pointer bg-transparent border-none z-60" onClick={() => setMobileOpen(!mobileOpen)}><span className={`block w-6 h-0.5 bg-foreground rounded transition-all duration-300 ${mobileOpen ? "rotate-45 translate-y-[7px]" : ""}`}></span><span className={`block w-6 h-0.5 bg-foreground rounded transition-all duration-300 ${mobileOpen ? "opacity-0" : ""}`}></span><span className={`block w-6 h-0.5 bg-foreground rounded transition-all duration-300 ${mobileOpen ? "-rotate-45 -translate-y-[7px]" : ""}`}></span></button>{mobileOpen && (<><div className="fixed inset-0 bg-black/50 z-40 md:hidden" onClick={() => setMobileOpen(false)}></div><div className="fixed top-0 right-0 w-72 h-full bg-background z-50 shadow-2xl p-8 pt-24 flex flex-col gap-2 md:hidden"><a href="/fiyatlar" className="block px-4 py-3 text-foreground hover:bg-accent rounded-lg text-lg no-underline transition" onClick={() => setMobileOpen(false)}>Fiyatlar</a><a href="/blog" className="block px-4 py-3 text-foreground hover:bg-accent rounded-lg text-lg no-underline transition" onClick={() => setMobileOpen(false)}>Blog</a><a href="/hakkimizda" className="block px-4 py-3 text-foreground hover:bg-accent rounded-lg text-lg no-underline transition" onClick={() => setMobileOpen(false)}>Hakkımda</a><a href="/teklif" className="block px-4 py-3 bg-primary text-primary-foreground font-medium hover:bg-primary/90 rounded-lg text-lg no-underline transition" onClick={() => setMobileOpen(false)}>Teklif Al</a></div></>)}</div></nav>
      <div className="container mx-auto px-4 py-12 max-w-4xl">
        <Breadcrumb items={[{label: "Hizmetler", href: "/"}, {label: "Denizli Apostil Tercüme"}]} />
        <h1 className="text-4xl font-bold text-primary mb-4">Denizli Apostil Tercüme | Yeminli Çeviri ve Apostil İşlemleri</h1>
        <p className="text-xl text-muted-foreground mb-8">Denizli'de apostil tercüme. Yurt dışı işlemleriniz için yeminli tercüman tarafından çevrilmiş ve apostil tasdikli belgeler. Lahey Apostil Sözleşmesi kapsamında geçerli.</p>
        <div className="grid md:grid-cols-3 gap-6 mb-12">
<div className="flex gap-4 p-6 bg-card rounded-xl border border-border"><Shield className="w-8 h-8 text-primary flex-shrink-0" /><div><h3 className="font-bold mb-2">Apostil Tasdiki</h3><p className="text-muted-foreground text-sm">Belgeleriniz Lahey Apostil Sözleşmesi kapsamında apostil tasdiki alır ve yurt dışında geçerli olur.</p></div></div><div className="flex gap-4 p-6 bg-card rounded-xl border border-border"><Clock className="w-8 h-8 text-primary flex-shrink-0" /><div><h3 className="font-bold mb-2">Süreç Takibi</h3><p className="text-muted-foreground text-sm">Apostil sürecini sizin yerinize takip ederim. Valilik ve kaymakamlık işlemleri dahil.</p></div></div><div className="flex gap-4 p-6 bg-card rounded-xl border border-border"><FileText className="w-8 h-8 text-primary flex-shrink-0" /><div><h3 className="font-bold mb-2">Geniş Belge Yelpazesi</h3><p className="text-muted-foreground text-sm">Diploma, evlilik cüzdanı, vukuatlı nüfus kayıt örneği, adli sicil ve daha fazlası.</p></div></div>
        </div>
<div className="bg-secondary/30 rounded-xl p-8 mb-8"><h2 className="text-2xl font-bold text-primary mb-4">Apostil Tercüme Nedir?</h2><p className="text-muted-foreground leading-relaxed mb-4">Apostil, bir belgenin yurt dışında geçerli olduğunu doğrulayan uluslararası bir tasdik mührüdür. Lahey Apostil Sözleşmesi'ne taraf ülkeler arasında geçerlidir. Türkiye'de apostil tasdiki valilikler ve kaymakamlıklar tarafından verilir.</p><p className="text-muted-foreground leading-relaxed mb-4">Apostil tercüme, öncelikle belgenin yeminli tercüman tarafından çevrilmesi, ardından valilik veya kaymakamlıktan apostil tasdiki alınması sürecidir. Bu işlem, belgenizin yurt dışındaki resmi kurumlarda geçerli olmasını sağlar.</p><p className="text-muted-foreground leading-relaxed mb-4">Apostil genellikle yurt dışı eğitim, evlilik, göçmenlik ve iş başvurularında istenir. Her ülkenin apostil gereksinimleri farklı olabilir — başvuru yapacağınız kurumun güncel şartlarını kontrol etmeniz önemlidir.</p></div><div className="bg-secondary/30 rounded-xl p-8 mb-8"><h2 className="text-2xl font-bold text-primary mb-4">Denizli'de Apostil Tercüme Süreci</h2><p className="text-muted-foreground leading-relaxed mb-4">Denizli merkezli yeminli tercüman olarak apostil tercüme hizmeti sunuyorum. Belgenizi çevirir, imzalar ve kaşelerim. Ardından Denizli Valiliği veya ilgili kaymakamlıktan apostil tasdiki almak için süreci sizin yerinize takip ederim.</p><p className="text-muted-foreground leading-relaxed mb-4">Apostil işlemi için belgenizin orijinalini veya noter tasdikli suretini sunmanız gerekir. Bu süreci önceden birlikte planlarız.</p><p className="text-muted-foreground leading-relaxed mb-4">Denizli dışından da apostil tercüme hizmeti alabilirsiniz. Kargo ile belge gönderimi ve teslimat mümkün.</p></div>
<div className="mb-8"><h2 className="text-2xl font-bold text-primary mb-6">Apostil Tercüme Süreci</h2><div className="space-y-4"><div className="flex gap-4 p-5 bg-card rounded-lg border border-border"><div className="flex-shrink-0 w-10 h-10 rounded-full bg-primary text-white flex items-center justify-center font-bold text-lg">1</div><div><h3 className="text-lg font-semibold text-primary mb-2">Belgenizi Gönderin</h3><p className="text-muted-foreground">Belgenizin orijinalini veya noter tasdikli suretini gönderin. Çeviri gerekip gerekmediğini birlikte belirleriz.</p></div></div><div className="flex gap-4 p-5 bg-card rounded-lg border border-border"><div className="flex-shrink-0 w-10 h-10 rounded-full bg-primary text-white flex items-center justify-center font-bold text-lg">2</div><div><h3 className="text-lg font-semibold text-primary mb-2">Çeviri ve Teklif</h3><p className="text-muted-foreground">Belgenizi çevirir, imzalar ve kaşelerim. Apostil işlem bedeli dahil net teklif veririm.</p></div></div><div className="flex gap-4 p-5 bg-card rounded-lg border border-border"><div className="flex-shrink-0 w-10 h-10 rounded-full bg-primary text-white flex items-center justify-center font-bold text-lg">3</div><div><h3 className="text-lg font-semibold text-primary mb-2">Apostil Başvurusu</h3><p className="text-muted-foreground">Belgenizi Denizli Valiliği veya ilgili kaymakamlığa sunar, apostil tasdiki alırım.</p></div></div><div className="flex gap-4 p-5 bg-card rounded-lg border border-border"><div className="flex-shrink-0 w-10 h-10 rounded-full bg-primary text-white flex items-center justify-center font-bold text-lg">4</div><div><h3 className="text-lg font-semibold text-primary mb-2">Teslim</h3><p className="text-muted-foreground">Apostil tasdikli belgenizi kargo veya dijital olarak teslim ederim.</p></div></div></div></div>
<div className="mb-8"><h2 className="text-2xl font-bold text-primary mb-6">Sıkça Sorulan Sorular</h2><div className="space-y-4"><div className="p-5 bg-card rounded-lg border border-border"><h3 className="font-bold text-primary mb-2">Apostil nedir ve ne için gerekir?</h3><p className="text-muted-foreground">Apostil, belgenizin yurt dışında geçerli olduğunu doğrulayan uluslararası bir tasdiktir. Lahey Apostil Sözleşmesi'ne taraf ülkelerde geçerlidir. Eğitim, evlilik, göçmenlik ve iş başvurularında istenir.</p></div><div className="p-5 bg-card rounded-lg border border-border"><h3 className="font-bold text-primary mb-2">Apostil ne kadar sürer?</h3><p className="text-muted-foreground">Valilik veya kaymakamlığın yoğunluğuna göre değişir. Genellikle 2-5 iş günü içinde tamamlanır.</p></div><div className="p-5 bg-card rounded-lg border border-border"><h3 className="font-bold text-primary mb-2">Apostil için orijinal belge mi gerekir?</h3><p className="text-muted-foreground">Evet, apostil için belgenin orijinali veya noter tasdikli sureti gerekir. Fotokopi yeterli değildir.</p></div><div className="p-5 bg-card rounded-lg border border-border"><h3 className="font-bold text-primary mb-2">Denizli dışından apostil tercüme alabilir miyim?</h3><p className="text-muted-foreground">Evet. Kargo ile belge gönderimi ve teslimat mümkün. Apostil sürecini sizin yerinize takip ederim.</p></div></div></div>
<div className="mb-8"><h2 className="text-2xl font-bold text-primary mb-6">İlgili Hizmetler</h2><div className="grid md:grid-cols-2 gap-4"><a href="/apostil-tercume" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Apostil Tercüme</a><a href="/denizli-yeminli-tercume" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Denizli Yeminli Tercüme</a><a href="/denizli-noter-onayli-tercume" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Denizli Noter Onaylı Tercüme</a><a href="/denizli-diploma-tercumesi" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Denizli Diploma Tercümesi</a><a href="/fiyatlar" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Çeviri Fiyatları</a><a href="/blog/apostil-vs-noter-onayli-ceviri" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Apostil vs Noter Onaylı Çeviri</a></div></div>
<div className="bg-primary text-primary-foreground rounded-xl p-8 text-center"><h2 className="text-2xl font-bold mb-4">Denizli Apostil Tercüme Teklifi Alın</h2><p className="mb-6 opacity-90">Belgenizi gönderin, çeviri ve apostil sürecini birlikte yönetelim.</p><div className="flex flex-col sm:flex-row gap-4 justify-center"><a href="/teklif" className="px-8 py-3 bg-accent hover:bg-accent/90 text-accent-foreground rounded-lg font-medium transition">Teklif Alın</a><a href="https://wa.me/905386295040" target="_blank" className="px-8 py-3 bg-green-500 hover:bg-green-600 text-white rounded-lg font-medium transition">WhatsApp ile Ulaşın</a></div></div>
      </div>
    </div>
  );
}