import { ArrowLeft, CheckCircle2, Shield, Clock, FileText, Globe } from "lucide-react";
import Breadcrumb from "@/components/Breadcrumb";
import { useState } from "react";
export default function DenizliVizeTercumesi() {
  const [mobileOpen, setMobileOpen] = useState(false);
  return (
    <div className="min-h-screen bg-background">
<nav className="sticky top-0 z-50 bg-background border-b border-border"><div className="container mx-auto px-4 py-4 flex justify-between items-center"><a href="/" className="flex items-center gap-2 text-muted-foreground hover:text-primary transition"><ArrowLeft className="w-5 h-5" /> Ana Sayfa</a><div className="hidden md:flex gap-8"><a href="/fiyatlar" className="text-foreground hover:text-primary transition">Fiyatlar</a><a href="/blog" className="text-foreground hover:text-primary transition">Blog</a><a href="/hakkimizda" className="text-foreground hover:text-primary transition">Hakkımda</a><a href="/teklif" className="bg-primary text-primary-foreground px-5 py-2 rounded-lg font-medium hover:bg-primary/90 transition no-underline">Teklif Al</a></div><button className="md:hidden flex flex-col gap-1.5 p-2 cursor-pointer bg-transparent border-none z-60" onClick={() => setMobileOpen(!mobileOpen)}><span className={`block w-6 h-0.5 bg-foreground rounded transition-all duration-300 ${mobileOpen ? "rotate-45 translate-y-[7px]" : ""}`}></span><span className={`block w-6 h-0.5 bg-foreground rounded transition-all duration-300 ${mobileOpen ? "opacity-0" : ""}`}></span><span className={`block w-6 h-0.5 bg-foreground rounded transition-all duration-300 ${mobileOpen ? "-rotate-45 -translate-y-[7px]" : ""}`}></span></button>{mobileOpen && (<><div className="fixed inset-0 bg-black/50 z-40 md:hidden" onClick={() => setMobileOpen(false)}></div><div className="fixed top-0 right-0 w-72 h-full bg-background z-50 shadow-2xl p-8 pt-24 flex flex-col gap-2 md:hidden"><a href="/fiyatlar" className="block px-4 py-3 text-foreground hover:bg-accent rounded-lg text-lg no-underline transition" onClick={() => setMobileOpen(false)}>Fiyatlar</a><a href="/blog" className="block px-4 py-3 text-foreground hover:bg-accent rounded-lg text-lg no-underline transition" onClick={() => setMobileOpen(false)}>Blog</a><a href="/hakkimizda" className="block px-4 py-3 text-foreground hover:bg-accent rounded-lg text-lg no-underline transition" onClick={() => setMobileOpen(false)}>Hakkımda</a><a href="/teklif" className="block px-4 py-3 bg-primary text-primary-foreground font-medium hover:bg-primary/90 rounded-lg text-lg no-underline transition" onClick={() => setMobileOpen(false)}>Teklif Al</a></div></>)}</div></nav>
      <div className="container mx-auto px-4 py-12 max-w-4xl">
        <Breadcrumb items={[{label: "Hizmetler", href: "/"}, {label: "Denizli Vize Tercümesi"}]} />
        <h1 className="text-4xl font-bold text-primary mb-4">Denizli Vize Tercümesi | İngilizce-Türkçe Yeminli Çeviri</h1>
        <p className="text-xl text-muted-foreground mb-8">Denizli'de vize başvurusu için belge çevirisi. Schengen, İngiltere, ABD ve Kanada vize başvuruları için yeminli tercüman tarafından çevrilmiş, imzalı ve kaşeli belgeler.</p>
        <div className="grid md:grid-cols-3 gap-6 mb-12">
<div className="flex gap-4 p-6 bg-card rounded-xl border border-border"><Shield className="w-8 h-8 text-primary flex-shrink-0" /><div><h3 className="font-bold mb-2">Konsolosluk Şartlarına Uygun</h3><p className="text-muted-foreground text-sm">Schengen, İngiltere, ABD ve Kanada vize başvuruları için uygun çeviri formatı.</p></div></div><div className="flex gap-4 p-6 bg-card rounded-xl border border-border"><Clock className="w-8 h-8 text-primary flex-shrink-0" /><div><h3 className="font-bold mb-2">Hızlı Teslimat</h3><p className="text-muted-foreground text-sm">Vize başvuru tarihine yetişmek için öncelikli olarak işleme alırım.</p></div></div><div className="flex gap-4 p-6 bg-card rounded-xl border border-border"><Globe className="w-8 h-8 text-primary flex-shrink-0" /><div><h3 className="font-bold mb-2">İngilizce-Türkçe</h3><p className="text-muted-foreground text-sm">Vize evraklarınız için İngilizce-Türkçe yeminli tercüme.</p></div></div>
        </div>
<div className="bg-secondary/30 rounded-xl p-8 mb-8"><h2 className="text-2xl font-bold text-primary mb-4">Vize Tercümesi Nedir?</h2><p className="text-muted-foreground leading-relaxed mb-4">Vize tercümesi, vize başvurusu için sunmanız gereken belgelerin — pasaport, banka dekontları, davetiye mektubu, otel rezervasyonu, SGK hizmet dökümü, tapu, araç ruhsatı gibi — yeminli tercüman tarafından İngilizce'ye çevrilmesidir.</p><p className="text-muted-foreground leading-relaxed mb-4">Her ülkenin vize başvurusu için farklı belge gereksinimleri vardır. Schengen vizesi, İngiltere vizesi, ABD vizesi ve Kanada vizesi için farklı formatlar ve gereksinimler geçerli olabilir.</p><p className="text-muted-foreground leading-relaxed mb-4">Vize başvurusu için çeviri yaptırırken, başvuru yapacağınız konsolosluğun güncel şartlarını kontrol etmeniz önemlidir. Bazı konsolosluklar yeminli tercüman imzasını kabul ederken, bazıları noter onayı veya apostil isteyebilir.</p></div><div className="bg-secondary/30 rounded-xl p-8 mb-8"><h2 className="text-2xl font-bold text-primary mb-4">Denizli'de Vize Tercümesi</h2><p className="text-muted-foreground leading-relaxed mb-4">Denizli merkezli yeminli tercüman olarak vize başvurusu için belge çevirisi yapıyorum. Denizli'den vize başvurusu yapacak olanlar için tüm evrakları eksiksiz çeviriyorum.</p><p className="text-muted-foreground leading-relaxed mb-4">Vize başvuru tarihine yetişmek için öncelikli olarak işleme alırım. Acil vize çevirilerinde aynı gün teslimat mümkün.</p><p className="text-muted-foreground leading-relaxed mb-4">Denizli dışından da vize çevirisi talep edebilirsiniz. Belgenizi WhatsApp'tan gönderin, çeviriyi dijital olarak teslim alabilirsiniz.</p></div>
<div className="mb-8"><h2 className="text-2xl font-bold text-primary mb-6">Vize Tercümesi Süreci</h2><div className="space-y-4"><div className="flex gap-4 p-5 bg-card rounded-lg border border-border"><div className="flex-shrink-0 w-10 h-10 rounded-full bg-primary text-white flex items-center justify-center font-bold text-lg">1</div><div><h3 className="text-lg font-semibold text-primary mb-2">Belgelerinizi Gönderin</h3><p className="text-muted-foreground">Vize başvurusu için gereken belgelerin fotoğrafını WhatsApp veya teklif formu üzerinden iletin.</p></div></div><div className="flex gap-4 p-5 bg-card rounded-lg border border-border"><div className="flex-shrink-0 w-10 h-10 rounded-full bg-primary text-white flex items-center justify-center font-bold text-lg">2</div><div><h3 className="text-lg font-semibold text-primary mb-2">Teklif Alın</h3><p className="text-muted-foreground">Belgeleri inceleyip net teklif veririm. Hangi belgelerin çevrilmesi gerektiğini birlikte belirleriz.</p></div></div><div className="flex gap-4 p-5 bg-card rounded-lg border border-border"><div className="flex-shrink-0 w-10 h-10 rounded-full bg-primary text-white flex items-center justify-center font-bold text-lg">3</div><div><h3 className="text-lg font-semibold text-primary mb-2">Çeviri ve İmza</h3><p className="text-muted-foreground">Belgelerinizi çevirir, imzalar ve kaşelerim. Konsolosluk şartlarına uygun format hazırlarım.</p></div></div><div className="flex gap-4 p-5 bg-card rounded-lg border border-border"><div className="flex-shrink-0 w-10 h-10 rounded-full bg-primary text-white flex items-center justify-center font-bold text-lg">4</div><div><h3 className="text-lg font-semibold text-primary mb-2">Teslim</h3><p className="text-muted-foreground">Çevrilmiş belgelerinizi dijital (PDF) veya kargo ile teslim ederim. Vize başvurunuz için hazırdır.</p></div></div></div></div>
<div className="mb-8"><h2 className="text-2xl font-bold text-primary mb-6">Sıkça Sorulan Sorular</h2><div className="space-y-4"><div className="p-5 bg-card rounded-lg border border-border"><h3 className="font-bold text-primary mb-2">Vize başvurusu için hangi belgelerin çevrilmesi gerekir?</h3><p className="text-muted-foreground">Pasaport, banka dekontları, davetiye mektubu, SGK hizmet dökümü, tapu, araç ruhsatı gibi belgeler sıkça istenir. Konsolosluğunuzun güncel belge listesini kontrol edin.</p></div><div className="p-5 bg-card rounded-lg border border-border"><h3 className="font-bold text-primary mb-2">Vize çevirisi ne kadar sürer?</h3><p className="text-muted-foreground">Belge sayısına göre değişir. 3-5 belge genellikle 1-2 iş günü içinde tamamlanır. Acil taleplerde aynı gün teslimat mümkün.</p></div><div className="p-5 bg-card rounded-lg border border-border"><h3 className="font-bold text-primary mb-2">Hangi ülkelerin vize başvurusu için çeviri yapıyorsunuz?</h3><p className="text-muted-foreground">Schengen, İngiltere, ABD ve Kanada vize başvuruları için çeviri yapıyorum. Diğer ülkeler için de danışabilirsiniz.</p></div><div className="p-5 bg-card rounded-lg border border-border"><h3 className="font-bold text-primary mb-2">Denizli dışından vize çevirisi yaptırabilir miyim?</h3><p className="text-muted-foreground">Evet. Belgelerinizi WhatsApp'tan gönderin, çeviriyi dijital olarak teslim alabilirsiniz.</p></div></div></div>
<div className="mb-8"><h2 className="text-2xl font-bold text-primary mb-6">İlgili Hizmetler</h2><div className="grid md:grid-cols-2 gap-4"><a href="/vize-ceviri" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Vize Çevirisi</a><a href="/denizli-pasaport-tercumesi" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Denizli Pasaport Tercümesi</a><a href="/denizli-yeminli-tercume" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Denizli Yeminli Tercüme</a><a href="/denizli-apostil-tercume" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Denizli Apostil Tercüme</a><a href="/fiyatlar" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Çeviri Fiyatları</a><a href="/blog/vize-formatlari" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Vize Çeviri Formatları Rehberi</a></div></div>
<div className="bg-primary text-primary-foreground rounded-xl p-8 text-center"><h2 className="text-2xl font-bold mb-4">Denizli Vize Tercümesi Teklifi Alın</h2><p className="mb-6 opacity-90">Vize belgelerinizi gönderin, konsolosluk şartlarına uygun çeviri hazırlayayım.</p><div className="flex flex-col sm:flex-row gap-4 justify-center"><a href="/teklif" className="px-8 py-3 bg-accent hover:bg-accent/90 text-accent-foreground rounded-lg font-medium transition">Teklif Alın</a><a href="https://wa.me/905386295040" target="_blank" className="px-8 py-3 bg-green-500 hover:bg-green-600 text-white rounded-lg font-medium transition">WhatsApp ile Ulaşın</a></div></div>
      </div>
    </div>
  );
}