import { ArrowLeft, CheckCircle2, Shield, Clock, FileText, Globe } from "lucide-react";
import Breadcrumb from "@/components/Breadcrumb";
import { useState } from "react";
export default function DenizliNoterOnayliTercume() {
  const [mobileOpen, setMobileOpen] = useState(false);
  return (
    <div className="min-h-screen bg-background">
<nav className="sticky top-0 z-50 bg-background border-b border-border"><div className="container mx-auto px-4 py-4 flex justify-between items-center"><a href="/" className="flex items-center gap-2 text-muted-foreground hover:text-primary transition"><ArrowLeft className="w-5 h-5" /> Ana Sayfa</a><div className="hidden md:flex gap-8"><a href="/fiyatlar" className="text-foreground hover:text-primary transition">Fiyatlar</a><a href="/blog" className="text-foreground hover:text-primary transition">Blog</a><a href="/hakkimizda" className="text-foreground hover:text-primary transition">Hakkımda</a><a href="/teklif" className="bg-primary text-primary-foreground px-5 py-2 rounded-lg font-medium hover:bg-primary/90 transition no-underline">Teklif Al</a></div><button className="md:hidden flex flex-col gap-1.5 p-2 cursor-pointer bg-transparent border-none z-60" onClick={() => setMobileOpen(!mobileOpen)}><span className={`block w-6 h-0.5 bg-foreground rounded transition-all duration-300 ${mobileOpen ? "rotate-45 translate-y-[7px]" : ""}`}></span><span className={`block w-6 h-0.5 bg-foreground rounded transition-all duration-300 ${mobileOpen ? "opacity-0" : ""}`}></span><span className={`block w-6 h-0.5 bg-foreground rounded transition-all duration-300 ${mobileOpen ? "-rotate-45 -translate-y-[7px]" : ""}`}></span></button>{mobileOpen && (<><div className="fixed inset-0 bg-black/50 z-40 md:hidden" onClick={() => setMobileOpen(false)}></div><div className="fixed top-0 right-0 w-72 h-full bg-background z-50 shadow-2xl p-8 pt-24 flex flex-col gap-2 md:hidden"><a href="/fiyatlar" className="block px-4 py-3 text-foreground hover:bg-accent rounded-lg text-lg no-underline transition" onClick={() => setMobileOpen(false)}>Fiyatlar</a><a href="/blog" className="block px-4 py-3 text-foreground hover:bg-accent rounded-lg text-lg no-underline transition" onClick={() => setMobileOpen(false)}>Blog</a><a href="/hakkimizda" className="block px-4 py-3 text-foreground hover:bg-accent rounded-lg text-lg no-underline transition" onClick={() => setMobileOpen(false)}>Hakkımda</a><a href="/teklif" className="block px-4 py-3 bg-primary text-primary-foreground font-medium hover:bg-primary/90 rounded-lg text-lg no-underline transition" onClick={() => setMobileOpen(false)}>Teklif Al</a></div></>)}</div></nav>
      <div className="container mx-auto px-4 py-12 max-w-4xl">
        <Breadcrumb items={[{label: "Hizmetler", href: "/"}, {label: "Denizli Noter Onaylı Tercüme"}]} />
        <h1 className="text-4xl font-bold text-primary mb-4">Denizli Noter Onaylı Tercüme | Yeminli Çeviri Hizmeti</h1>
        <p className="text-xl text-muted-foreground mb-8">Denizli'de noter onaylı tercüme. Yeminli tercüman tarafından çevrilip noter tasdikli belgeler. Vize, eğitim ve resmi işlemler için hızlı ve güvenilir hizmet.</p>
        <div className="grid md:grid-cols-3 gap-6 mb-12">
<div className="flex gap-4 p-6 bg-card rounded-xl border border-border"><Shield className="w-8 h-8 text-primary flex-shrink-0" /><div><h3 className="font-bold mb-2">Noter Tasdiki</h3><p className="text-muted-foreground text-sm">Çeviri yeminli tercüman tarafından yapılır ve noter tarafından tasdik edilir. Resmi geçerlilik tamdır.</p></div></div><div className="flex gap-4 p-6 bg-card rounded-xl border border-border"><Clock className="w-8 h-8 text-primary flex-shrink-0" /><div><h3 className="font-bold mb-2">Hızlı Süreç</h3><p className="text-muted-foreground text-sm">Noter onayı sürecini sizin yerinize takip ederim. Belgenizi notere götürmenize gerek yok.</p></div></div><div className="flex gap-4 p-6 bg-card rounded-xl border border-border"><FileText className="w-8 h-8 text-primary flex-shrink-0" /><div><h3 className="font-bold mb-2">Geniş Belge Yelpazesi</h3><p className="text-muted-foreground text-sm">Pasaport, diploma, evlilik cüzdanı, vukuatlı nüfus kayıt örneği ve daha fazlası.</p></div></div>
        </div>
<div className="bg-secondary/30 rounded-xl p-8 mb-8"><h2 className="text-2xl font-bold text-primary mb-4">Noter Onaylı Tercüme Nedir?</h2><p className="text-muted-foreground leading-relaxed mb-4">Noter onaylı tercüme, yeminli tercüman tarafından yapılan çevirinin noter tarafından tasdik edilmesidir. Noter, tercümanın imzasını ve kaşesini doğrular ve belgeye resmi geçerlilik kazandırır.</p><p className="text-muted-foreground leading-relaxed mb-4">Noter onayı, bazı kurumların ve ülkelerin şart koştuğu ek bir güvenlik adımıdır. Yeminli tercüme tek başına yeterli olmadığında, noter onayı gerekir.</p><p className="text-muted-foreground leading-relaxed mb-4">Denizli'deki noterlerle süreci bizzat takip ederim. Sizin notere gitmenize gerek yok — belgenizi gönderin, gerisini ben hallederim.</p></div><div className="bg-secondary/30 rounded-xl p-8 mb-8"><h2 className="text-2xl font-bold text-primary mb-4">Denizli'de Noter Onaylı Tercüme Süreci</h2><p className="text-muted-foreground leading-relaxed mb-4">Denizli'deki noterlerle çalışıyorum ve noter onayı sürecini bizzat takip ediyorum. Belgenizi çevirip notere götürür, tasdik işlemini tamamlar ve size teslim ederim.</p><p className="text-muted-foreground leading-relaxed mb-4">Noter harç ve işlem bedeli, gerçek noter makbuzuyla teyit edilir ve çeviri ücretine dahil değildir. Önceden net bilgi veririm.</p><p className="text-muted-foreground leading-relaxed mb-4">Denizli dışından da bu hizmeti alabilirsiniz. Kargo ile belge gönderimi ve teslimat mümkün.</p></div>
<div className="mb-8"><h2 className="text-2xl font-bold text-primary mb-6">Noter Onaylı Tercüme Süreci</h2><div className="space-y-4"><div className="flex gap-4 p-5 bg-card rounded-lg border border-border"><div className="flex-shrink-0 w-10 h-10 rounded-full bg-primary text-white flex items-center justify-center font-bold text-lg">1</div><div><h3 className="text-lg font-semibold text-primary mb-2">Belgenizi Gönderin</h3><p className="text-muted-foreground">Belgenizin fotoğrafını WhatsApp veya teklif formu üzerinden iletin.</p></div></div><div className="flex gap-4 p-5 bg-card rounded-lg border border-border"><div className="flex-shrink-0 w-10 h-10 rounded-full bg-primary text-white flex items-center justify-center font-bold text-lg">2</div><div><h3 className="text-lg font-semibold text-primary mb-2">Teklif ve Onay</h3><p className="text-muted-foreground">Çeviri ve noter onayı için net teklif veririm. Onayladığınızda süreç başlar.</p></div></div><div className="flex gap-4 p-5 bg-card rounded-lg border border-border"><div className="flex-shrink-0 w-10 h-10 rounded-full bg-primary text-white flex items-center justify-center font-bold text-lg">3</div><div><h3 className="text-lg font-semibold text-primary mb-2">Çeviri ve Noter Tasdiki</h3><p className="text-muted-foreground">Belgenizi çevirir, imzalar ve kaşelerim. Sonra notere götürür, tasdik işlemini tamamlarım.</p></div></div><div className="flex gap-4 p-5 bg-card rounded-lg border border-border"><div className="flex-shrink-0 w-10 h-10 rounded-full bg-primary text-white flex items-center justify-center font-bold text-lg">4</div><div><h3 className="text-lg font-semibold text-primary mb-2">Teslim</h3><p className="text-muted-foreground">Noter tasdikli belgenizi dijital veya kargo ile teslim ederim.</p></div></div></div></div>
<div className="mb-8"><h2 className="text-2xl font-bold text-primary mb-6">Sıkça Sorulan Sorular</h2><div className="space-y-4"><div className="p-5 bg-card rounded-lg border border-border"><h3 className="font-bold text-primary mb-2">Noter onaylı tercüme ile yeminli tercüme arasındaki fark nedir?</h3><p className="text-muted-foreground">Yeminli tercümede tercüman imzası yeterlidir. Noter onaylı tercümede ise noter, tercümanın imzasını tasdik eder. Bazı kurumlar noter onayını şart koşar.</p></div><div className="p-5 bg-card rounded-lg border border-border"><h3 className="font-bold text-primary mb-2">Noter onayı ne kadar sürer?</h3><p className="text-muted-foreground">Çeviri tamamlandıktan sonra noter onayı genellikle aynı gün içinde tamamlanır. Noterin yoğunluğuna göre değişebilir.</p></div><div className="p-5 bg-card rounded-lg border border-border"><h3 className="font-bold text-primary mb-2">Noter bedeli ayrı mı?</h3><p className="text-muted-foreground">Evet. Noter harç ve işlem bedeli, gerçek makbuzla teyit edilir ve çeviri ücretine dahil değildir.</p></div><div className="p-5 bg-card rounded-lg border border-border"><h3 className="font-bold text-primary mb-2">Denizli dışından noter onaylı tercüme alabilir miyim?</h3><p className="text-muted-foreground">Evet. Kargo ile belge gönderimi ve teslimat mümkün. Tüm süreci sizin yerinize takip ederim.</p></div></div></div>
<div className="mb-8"><h2 className="text-2xl font-bold text-primary mb-6">İlgili Hizmetler</h2><div className="grid md:grid-cols-2 gap-4"><a href="/noter-onayli-tercume" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Noter Onaylı Tercüme</a><a href="/denizli-yeminli-tercume" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Denizli Yeminli Tercüme</a><a href="/denizli-apostil-tercume" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Denizli Apostil Tercüme</a><a href="/fiyatlar" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Çeviri Fiyatları</a><a href="/teklif" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Teklif Al</a><a href="/blog/noter-onayli-ceviri" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Noter Onaylı Çeviri Rehberi</a></div></div>
<div className="bg-primary text-primary-foreground rounded-xl p-8 text-center"><h2 className="text-2xl font-bold mb-4">Denizli Noter Onaylı Tercüme Teklifi Alın</h2><p className="mb-6 opacity-90">Belgenizi gönderin, çeviri ve noter onayı sürecini birlikte yönetelim.</p><div className="flex flex-col sm:flex-row gap-4 justify-center"><a href="/teklif" className="px-8 py-3 bg-accent hover:bg-accent/90 text-accent-foreground rounded-lg font-medium transition">Teklif Alın</a><a href="https://wa.me/905386295040" target="_blank" className="px-8 py-3 bg-green-500 hover:bg-green-600 text-white rounded-lg font-medium transition">WhatsApp ile Ulaşın</a></div></div>
      </div>
    </div>
  );
}