import { ArrowLeft, CheckCircle2, Shield, Clock, FileText, Globe } from "lucide-react";
import Breadcrumb from "@/components/Breadcrumb";
import { useState } from "react";
export default function DenizliDiplomaTercumesi() {
  const [mobileOpen, setMobileOpen] = useState(false);
  return (
    <div className="min-h-screen bg-background">
<nav className="sticky top-0 z-50 bg-background border-b border-border"><div className="container mx-auto px-4 py-4 flex justify-between items-center"><a href="/" className="flex items-center gap-2 text-muted-foreground hover:text-primary transition"><ArrowLeft className="w-5 h-5" /> Ana Sayfa</a><div className="hidden md:flex gap-8"><a href="/fiyatlar" className="text-foreground hover:text-primary transition">Fiyatlar</a><a href="/blog" className="text-foreground hover:text-primary transition">Blog</a><a href="/hakkimizda" className="text-foreground hover:text-primary transition">Hakkımda</a><a href="/teklif" className="bg-primary text-primary-foreground px-5 py-2 rounded-lg font-medium hover:bg-primary/90 transition no-underline">Teklif Al</a></div><button className="md:hidden flex flex-col gap-1.5 p-2 cursor-pointer bg-transparent border-none z-60" onClick={() => setMobileOpen(!mobileOpen)}><span className={`block w-6 h-0.5 bg-foreground rounded transition-all duration-300 ${mobileOpen ? "rotate-45 translate-y-[7px]" : ""}`}></span><span className={`block w-6 h-0.5 bg-foreground rounded transition-all duration-300 ${mobileOpen ? "opacity-0" : ""}`}></span><span className={`block w-6 h-0.5 bg-foreground rounded transition-all duration-300 ${mobileOpen ? "-rotate-45 -translate-y-[7px]" : ""}`}></span></button>{mobileOpen && (<><div className="fixed inset-0 bg-black/50 z-40 md:hidden" onClick={() => setMobileOpen(false)}></div><div className="fixed top-0 right-0 w-72 h-full bg-background z-50 shadow-2xl p-8 pt-24 flex flex-col gap-2 md:hidden"><a href="/fiyatlar" className="block px-4 py-3 text-foreground hover:bg-accent rounded-lg text-lg no-underline transition" onClick={() => setMobileOpen(false)}>Fiyatlar</a><a href="/blog" className="block px-4 py-3 text-foreground hover:bg-accent rounded-lg text-lg no-underline transition" onClick={() => setMobileOpen(false)}>Blog</a><a href="/hakkimizda" className="block px-4 py-3 text-foreground hover:bg-accent rounded-lg text-lg no-underline transition" onClick={() => setMobileOpen(false)}>Hakkımda</a><a href="/teklif" className="block px-4 py-3 bg-primary text-primary-foreground font-medium hover:bg-primary/90 rounded-lg text-lg no-underline transition" onClick={() => setMobileOpen(false)}>Teklif Al</a></div></>)}</div></nav>
      <div className="container mx-auto px-4 py-12 max-w-4xl">
        <Breadcrumb items={[{label: "Hizmetler", href: "/"}, {label: "Denizli Diploma Tercümesi"}]} />
        <h1 className="text-4xl font-bold text-primary mb-4">Denizli Diploma Tercümesi | İngilizce-Türkçe Yeminli Çeviri</h1>
        <p className="text-xl text-muted-foreground mb-8">Denizli'de diploma ve transkript çevirisi. Yeminli tercüman tarafından İngilizce veya Türkçe'ye çevrilmiş diploma tercümesi. Yurt dışı eğitim başvuruları için hızlı teslimat.</p>
        <div className="grid md:grid-cols-3 gap-6 mb-12">
<div className="flex gap-4 p-6 bg-card rounded-xl border border-border"><Shield className="w-8 h-8 text-primary flex-shrink-0" /><div><h3 className="font-bold mb-2">Resmi Geçerlilik</h3><p className="text-muted-foreground text-sm">Yeminli tercüman imzası yurt dışı üniversiteler ve kurumlarda kabul edilir.</p></div></div><div className="flex gap-4 p-6 bg-card rounded-xl border border-border"><Clock className="w-8 h-8 text-primary flex-shrink-0" /><div><h3 className="font-bold mb-2">Hızlı Teslimat</h3><p className="text-muted-foreground text-sm">Diploma ve transkript çevirisi genellikle 1-2 iş günü içinde tamamlanır.</p></div></div><div className="flex gap-4 p-6 bg-card rounded-xl border border-border"><FileText className="w-8 h-8 text-primary flex-shrink-0" /><div><h3 className="font-bold mb-2">Diploma + Transkript</h3><p className="text-muted-foreground text-sm">Diploma ve transkript birlikte çevrilir, tutarlı terminoloji sağlanır.</p></div></div>
        </div>
<div className="bg-secondary/30 rounded-xl p-8 mb-8"><h2 className="text-2xl font-bold text-primary mb-4">Diploma Tercümesi Nedir?</h2><p className="text-muted-foreground leading-relaxed mb-4">Diploma tercümesi, diplomanızdaki bilgilerin — okul adı, bölüm, derece, notlandırma sistemi, tarihler — yeminli tercüman tarafından İngilizce'ye veya Türkçe'ye çevrilmesidir. Çeviri imzalanır ve kaşelenir.</p><p className="text-muted-foreground leading-relaxed mb-4">Diploma çevirisi, yurt dışı yüksek lisans başvurularında, denklik işlemlerinde, iş başvurularında ve göçmenlik dosyalarında sıkça talep edilir.</p><p className="text-muted-foreground leading-relaxed mb-4">Transkript çevirisi de genellikle diploma ile birlikte istenir. İkisini birlikte çevirmek, terminoloji tutarlılığını sağlar ve süreci hızlandırır.</p></div><div className="bg-secondary/30 rounded-xl p-8 mb-8"><h2 className="text-2xl font-bold text-primary mb-4">Denizli'de Diploma Tercümesi</h2><p className="text-muted-foreground leading-relaxed mb-4">Denizli merkezli yeminli tercüman olarak diploma ve transkript çevirisi yapıyorum. Pamukkale Üniversitesi mezunları ve Denizli'deki diğer kurumlardan diploma sahipleri için çeviri hizmeti sunuyorum.</p><p className="text-muted-foreground leading-relaxed mb-4">Diplomanızın fotoğrafını WhatsApp'tan göndermeniz yeterli. Tüm bilgileri eksiksiz çevirir, notlandırma sistemini doğru şekilde aktarırım.</p><p className="text-muted-foreground leading-relaxed mb-4">Denizli dışından da hizmet veriyorum. Yurt dışına gidecek öğrenciler ve profesyoneller için diploma çevirisi hazırlıyorum.</p></div>
<div className="mb-8"><h2 className="text-2xl font-bold text-primary mb-6">Diploma Tercümesi Süreci</h2><div className="space-y-4"><div className="flex gap-4 p-5 bg-card rounded-lg border border-border"><div className="flex-shrink-0 w-10 h-10 rounded-full bg-primary text-white flex items-center justify-center font-bold text-lg">1</div><div><h3 className="text-lg font-semibold text-primary mb-2">Diploma Fotoğrafını Gönderin</h3><p className="text-muted-foreground">Diploma ve transkriptinizin net fotoğrafını WhatsApp veya teklif formu üzerinden iletin.</p></div></div><div className="flex gap-4 p-5 bg-card rounded-lg border border-border"><div className="flex-shrink-0 w-10 h-10 rounded-full bg-primary text-white flex items-center justify-center font-bold text-lg">2</div><div><h3 className="text-lg font-semibold text-primary mb-2">Teklif Alın</h3><p className="text-muted-foreground">Belgeyi inceleyip net teklif veririm. Onayladığınızda çeviri başlar.</p></div></div><div className="flex gap-4 p-5 bg-card rounded-lg border border-border"><div className="flex-shrink-0 w-10 h-10 rounded-full bg-primary text-white flex items-center justify-center font-bold text-lg">3</div><div><h3 className="text-lg font-semibold text-primary mb-2">Çeviri ve İmza</h3><p className="text-muted-foreground">Diploma ve transkriptinizi çevirir, imzalar ve kaşelerim.</p></div></div><div className="flex gap-4 p-5 bg-card rounded-lg border border-border"><div className="flex-shrink-0 w-10 h-10 rounded-full bg-primary text-white flex items-center justify-center font-bold text-lg">4</div><div><h3 className="text-lg font-semibold text-primary mb-2">Teslim</h3><p className="text-muted-foreground">Çevrilmiş belgelerinizi dijital (PDF) veya kargo ile teslim ederim.</p></div></div></div></div>
<div className="mb-8"><h2 className="text-2xl font-bold text-primary mb-6">Sıkça Sorulan Sorular</h2><div className="space-y-4"><div className="p-5 bg-card rounded-lg border border-border"><h3 className="font-bold text-primary mb-2">Diploma çevirisi ne kadar sürer?</h3><p className="text-muted-foreground">Diploma ve transkript birlikte genellikle 1-2 iş günü içinde tamamlanır. Acil taleplerde aynı gün teslimat mümkün.</p></div><div className="p-5 bg-card rounded-lg border border-border"><h3 className="font-bold text-primary mb-2">Transkript çevirisi ayrı ücretli mi?</h3><p className="text-muted-foreground">Transkript ayrı bir belgedir ve ayrı fiyatlandırılır. Diploma ve transkript birlikte çevrilirse indirimli fiyat uygulanır.</p></div><div className="p-5 bg-card rounded-lg border border-border"><h3 className="font-bold text-primary mb-2">Denizli dışından diploma çevirisi yaptırabilir miyim?</h3><p className="text-muted-foreground">Evet. Diplomanızın fotoğrafını WhatsApp'tan gönderin, çeviriyi dijital olarak teslim alabilirsiniz.</p></div><div className="p-5 bg-card rounded-lg border border-border"><h3 className="font-bold text-primary mb-2">Notlandırma sistemi nasıl çevrilir?</h3><p className="text-muted-foreground">Türk notlandırma sistemi (0-100) İngilizce notlandırma sistemine doğru şekilde aktarılır. Kurumunuzun istediği formata uyarlarım.</p></div></div></div>
<div className="mb-8"><h2 className="text-2xl font-bold text-primary mb-6">İlgili Hizmetler</h2><div className="grid md:grid-cols-2 gap-4"><a href="/diploma-ceviri" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Diploma Çevirisi</a><a href="/transkript-ceviri" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Transkript Çevirisi</a><a href="/denizli-yeminli-tercume" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Denizli Yeminli Tercüme</a><a href="/denizli-apostil-tercume" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Denizli Apostil Tercüme</a><a href="/fiyatlar" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Çeviri Fiyatları</a><a href="/teklif" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Teklif Al</a></div></div>
<div className="bg-primary text-primary-foreground rounded-xl p-8 text-center"><h2 className="text-2xl font-bold mb-4">Denizli Diploma Tercümesi Teklifi Alın</h2><p className="mb-6 opacity-90">Diploma ve transkriptinizin fotoğrafını gönderin, hemen teklif alırım.</p><div className="flex flex-col sm:flex-row gap-4 justify-center"><a href="/teklif" className="px-8 py-3 bg-accent hover:bg-accent/90 text-accent-foreground rounded-lg font-medium transition">Teklif Alın</a><a href="https://wa.me/905386295040" target="_blank" className="px-8 py-3 bg-green-500 hover:bg-green-600 text-white rounded-lg font-medium transition">WhatsApp ile Ulaşın</a></div></div>
      </div>
    </div>
  );
}