import { CheckCircle2, Shield, Clock, Globe, Zap, Lock } from "lucide-react";
import Navbar from "@/components/home/Navbar";
import Breadcrumb from "@/components/Breadcrumb";
import { useState } from "react";
export default function TranskriptCeviri() {
  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <div className="container mx-auto px-4 py-12 max-w-4xl">
        <Breadcrumb items={[{label: "Hizmetler", href: "/"}, {label: "Transkript Çevirisi"}]} />
        <h1 className="text-4xl font-bold text-primary mb-4">Transkript Çevirisi | İngilizce-Türkçe Yeminli Tercüme</h1>
        <p className="text-xl text-muted-foreground mb-8">Transkriptinizin yeminli tercüman tarafından İngilizce veya Türkçe'ye çevirisi. Yurt dışı eğitim başvuruları için hızlı, güvenilir ve doğru çeviri hizmeti.</p>
        <div className="grid md:grid-cols-3 gap-6 mb-12">
<div className="flex gap-4 p-6 bg-card rounded-xl border border-border"><Shield className="w-8 h-8 text-primary flex-shrink-0" /><div><h3 className="font-bold mb-2">Resmi Geçerlilik</h3><p className="text-muted-foreground text-sm">Yeminli tercüman imzası yurt dışı üniversiteler ve kurumlarda kabul edilir; başvuru yapacağınız kurumun güncel şartlarını kontrol etmeniz gerekir.</p></div></div><div className="flex gap-4 p-6 bg-card rounded-xl border border-border"><Clock className="w-8 h-8 text-primary flex-shrink-0" /><div><h3 className="font-bold mb-2">Aynı Gün Teslimat</h3><p className="text-muted-foreground text-sm">Transkript çevirisi genellikle aynı gün içinde tamamlanır.</p></div></div><div className="flex gap-4 p-6 bg-card rounded-xl border border-border"><Globe className="w-8 h-8 text-primary flex-shrink-0" /><div><h3 className="font-bold mb-2">İngilizce-Türkçe</h3><p className="text-muted-foreground text-sm">İngilizce-Türkçe dil çiftinde uzman yeminli tercüme.</p></div></div>
        </div>
<div className="bg-secondary/30 rounded-xl p-8 mb-8"><h2 className="text-2xl font-bold text-primary mb-4">Transkript Çevirisi Nedir?</h2><p className="text-muted-foreground leading-relaxed mb-4">Transkript çevirisi, üniversite transkriptinizdeki ders adları, notlar, kredi saatleri ve akademik bilgilerin yeminli tercüman tarafından İngilizce'ye veya Türkçe'ye çevrilmesidir. Bu çeviri, yeminli tercüman tarafından imzalanır ve kaşelenir.</p><p className="text-muted-foreground leading-relaxed mb-4">Transkript çevirisi, özellikle yurt dışı üniversite başvurularında, master ve PhD başvurularında, denklik işlemlerinde ve akademik başvurularda talep edilir. Yanlış çeviri, başvuru sürecinizin gecikmesine veya reddedilmesine neden olabilir.</p><p className="text-muted-foreground leading-relaxed mb-4">İngilizce-Türkçe dil çiftinde transkript çevirisi yapıyorum. Transkriptinizdeki tüm akademik bilgileri eksiksiz ve doğru şekilde çevirip imzalıyor ve kaşeliyorum.</p></div>
<div className="bg-secondary/30 rounded-xl p-8 mb-8"><h2 className="text-2xl font-bold text-primary mb-4">Transkript Çevirisi Nerede Kullanılır?</h2><div className="grid md:grid-cols-2 gap-4"><div className="flex items-center gap-3 p-3 bg-card rounded-lg border border-border"><CheckCircle2 className="w-5 h-5 text-primary flex-shrink-0" /><span className="text-foreground">Yurt dışı üniversite başvuruları</span></div><div className="flex items-center gap-3 p-3 bg-card rounded-lg border border-border"><CheckCircle2 className="w-5 h-5 text-primary flex-shrink-0" /><span className="text-foreground">Master ve PhD başvuruları</span></div><div className="flex items-center gap-3 p-3 bg-card rounded-lg border border-border"><CheckCircle2 className="w-5 h-5 text-primary flex-shrink-0" /><span className="text-foreground">Erasmus ve değişim programları</span></div><div className="flex items-center gap-3 p-3 bg-card rounded-lg border border-border"><CheckCircle2 className="w-5 h-5 text-primary flex-shrink-0" /><span className="text-foreground">Diploma denklik işlemleri</span></div><div className="flex items-center gap-3 p-3 bg-card rounded-lg border border-border"><CheckCircle2 className="w-5 h-5 text-primary flex-shrink-0" /><span className="text-foreground">Akademik iş başvuruları</span></div><div className="flex items-center gap-3 p-3 bg-card rounded-lg border border-border"><CheckCircle2 className="w-5 h-5 text-primary flex-shrink-0" /><span className="text-foreground">Burs başvuruları</span></div></div></div>
<div className="mb-8"><h2 className="text-2xl font-bold text-primary mb-6">Transkript Çevirisi Süreci: Adım Adım</h2><div className="space-y-4"><div className="flex gap-4 p-5 bg-card rounded-lg border border-border"><div className="flex-shrink-0 w-10 h-10 rounded-full bg-primary text-white flex items-center justify-center font-bold text-lg">1</div><div><h3 className="text-lg font-semibold text-primary mb-2">Transkripti Gönderin</h3><p className="text-muted-foreground">Transkriptinizin fotoğrafını veya taranmış halini WhatsApp veya teklif formu üzerinden iletin. Tüm sayfaların net görünmesi gerekir.</p></div></div><div className="flex gap-4 p-5 bg-card rounded-lg border border-border"><div className="flex-shrink-0 w-10 h-10 rounded-full bg-primary text-white flex items-center justify-center font-bold text-lg">2</div><div><h3 className="text-lg font-semibold text-primary mb-2">Fiyat Teklifi</h3><p className="text-muted-foreground">Transkript çevirisi için belgeyi inceleyip net teklif veririm. Teklifi onayladığınızda çeviri süreci başlar.</p></div></div><div className="flex gap-4 p-5 bg-card rounded-lg border border-border"><div className="flex-shrink-0 w-10 h-10 rounded-full bg-primary text-white flex items-center justify-center font-bold text-lg">3</div><div><h3 className="text-lg font-semibold text-primary mb-2">Çeviri ve İmza</h3><p className="text-muted-foreground">Transkriptinizdeki tüm ders adları, notlar ve akademik bilgileri çevirir, imzalar ve kaşelerim. Çeviri resmi belge niteliği kazanır.</p></div></div><div className="flex gap-4 p-5 bg-card rounded-lg border border-border"><div className="flex-shrink-0 w-10 h-10 rounded-full bg-primary text-white flex items-center justify-center font-bold text-lg">4</div><div><h3 className="text-lg font-semibold text-primary mb-2">Teslim</h3><p className="text-muted-foreground">Çevrilmiş transkriptiniz dijital (PDF) olarak veya kargo/kurye ile adresinize teslim edilir. Belgeniz başvurular için hazırdır.</p></div></div></div></div>
<div className="bg-secondary/30 rounded-xl p-8 mb-8"><h2 className="text-2xl font-bold text-primary mb-4">Transkript Çevirisi Fiyatları</h2><p className="text-muted-foreground leading-relaxed mb-4">Transkript çevirisi için belgeyi inceleyip net teklif veririm. Sayfa sayısı ve içerik yoğunluğu fiyatı belirler. Noter onayı gerektiğinde, gerçek noter bedeli makbuzla teyit edilir ve işlem/takip bedeli ayrı kalemdir.</p><p className="text-muted-foreground leading-relaxed mb-4">Net teklif için transkriptinizin fotoğrafını WhatsApp'tan gönderin. Belge türünü, noter ve apostil ihtiyacını inceleyip dönüş yapıyorum.</p></div>
<div className="mb-8"><h2 className="text-2xl font-bold text-primary mb-6">Sıkça Sorulan Sorular</h2><div className="space-y-4"><div className="p-5 bg-card rounded-lg border border-border"><h3 className="font-bold text-primary mb-2">Transkript çevirisi nedir ve ne için gerekir?</h3><p className="text-muted-foreground">Transkript çevirisi, üniversite transkriptinizdeki akademik bilgilerin yeminli tercüman tarafından İngilizce'ye veya Türkçe'ye çevrilmesidir. Yurt dışı eğitim başvuruları, denklik işlemleri ve akademik başvurularda istenir.</p></div><div className="p-5 bg-card rounded-lg border border-border"><h3 className="font-bold text-primary mb-2">Transkript çevirisi yeminli tercüman tarafından mı yapılmalıdır?</h3><p className="text-muted-foreground">Evet, yurt dışı üniversiteler ve kurumlar transkript çevirisinin yeminli tercüman tarafından yapılmasını ve imzalanmasını ister. Yeminli tercüman imzası, çevirinin doğru ve eksiksiz olduğunu taahhüt eder.</p></div><div className="p-5 bg-card rounded-lg border border-border"><h3 className="font-bold text-primary mb-2">Transkript çevirisi ne kadar sürer?</h3><p className="text-muted-foreground">Transkript çevirisi genellikle aynı gün veya 1 iş günü içinde tamamlanır. Sayfa sayısı fazla ise süre uzayabilir.</p></div><div className="p-5 bg-card rounded-lg border border-border"><h3 className="font-bold text-primary mb-2">Transkript çevirisi için noter onayı gerekir mi?</h3><p className="text-muted-foreground">Çoğu durumda yeminli tercüman imzası yeterlidir. Ancak bazı ülkeler ve kurumlar noter onayını şart koşabilir. Başvuru yapacağınız kuruma danışmanızı öneririm.</p></div><div className="p-5 bg-card rounded-lg border border-border"><h3 className="font-bold text-primary mb-2">Transkript çevirisi ücreti ne kadar?</h3><p className="text-muted-foreground">Transkript çevirisi ücreti belge görülerek belirlenir. Belgenizin fotoğrafını WhatsApp'tan gönderin; net teklif alırsınız.</p></div></div></div>
<div className="mb-8"><h2 className="text-2xl font-bold text-primary mb-6">İlgili Blog Yazıları</h2><div className="grid md:grid-cols-2 gap-4 mb-8"><a href="/blog/akademik-ceviri" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Akademik Çeviri Rehberi</a><a href="/blog/yeminli-tercume" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Yeminli Tercüme Süreci</a><a href="/blog/vize-formatlari" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Vize Çeviri Formatları Rehberi</a></div>
<h2 className="text-2xl font-bold text-primary mb-6">Diğer Hizmetler</h2><div className="grid md:grid-cols-2 gap-4"><a href="/yeminli-tercume" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Yeminli Tercüme</a><a href="/ingilizce-turkce-ceviri" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">İngilizce-Türkçe Çeviri</a><a href="/pasaport-ceviri" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Pasaport Çevirisi</a><a href="/diploma-ceviri" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Diploma Çevirisi</a><a href="/vize-ceviri" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Vize Çevirisi</a><a href="/teknik-ceviri" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Teknik Çeviri</a><a href="/akademik-ceviri" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Akademik Çeviri</a><a href="/acil-tercume" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Acil Tercüme</a><a href="/fiyatlar" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Çeviri Fiyatları</a><a href="/teklif" className="block px-4 py-3 bg-card rounded-lg border border-border hover:border-primary hover:shadow-md transition no-underline text-foreground">Teklif Al</a></div></div>
<div className="bg-primary text-primary-foreground rounded-xl p-8 text-center"><h2 className="text-2xl font-bold mb-4">Transkript Çevirisi Teklifi Alın</h2><p className="mb-6 opacity-90">Transkriptinizin fotoğrafını gönderin, net teklif alın.</p><div className="flex flex-col sm:flex-row gap-4 justify-center"><a href="/teklif" className="px-8 py-3 bg-accent hover:bg-accent/90 text-accent-foreground rounded-lg font-medium transition">Teklif Al</a><a href="https://wa.me/905386295040" target="_blank" className="px-8 py-3 bg-green-500 hover:bg-green-600 text-white rounded-lg font-medium transition">WhatsApp'tan Gönderin</a></div></div>
      </div>
    </div>
  );
}